/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyPolicyDothtmlRouteImport } from './routes/privacy-policy[.]html'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsDothtmlRouteImport } from './routes/terms[.]html'
import { Route as ThankyouDothtmlRouteImport } from './routes/thankyou[.]html'
import { Route as Lp2BhkRouteImport } from './routes/lp.2-bhk'
import { Route as Lp3BhkRouteImport } from './routes/lp.3-bhk'
import { Route as Lp3BhkDuplexRouteImport } from './routes/lp.3-bhk-duplex'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyDothtmlRoute = PrivacyPolicyDothtmlRouteImport.update({
  id: '/privacy-policy.html',
  path: '/privacy-policy.html',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsDothtmlRoute = TermsDothtmlRouteImport.update({
  id: '/terms.html',
  path: '/terms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouDothtmlRoute = ThankyouDothtmlRouteImport.update({
  id: '/thankyou.html',
  path: '/thankyou.html',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp2BhkRoute = Lp2BhkRouteImport.update({
  id: '/lp/2-bhk',
  path: '/lp/2-bhk',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp3BhkRoute = Lp3BhkRouteImport.update({
  id: '/lp/3-bhk',
  path: '/lp/3-bhk',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp3BhkDuplexRoute = Lp3BhkDuplexRouteImport.update({
  id: '/lp/3-bhk-duplex',
  path: '/lp/3-bhk-duplex',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy-policy.html': typeof PrivacyPolicyDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/thankyou.html': typeof ThankyouDothtmlRoute
  '/lp/2-bhk': typeof Lp2BhkRoute
  '/lp/3-bhk': typeof Lp3BhkRoute
  '/lp/3-bhk-duplex': typeof Lp3BhkDuplexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy-policy.html': typeof PrivacyPolicyDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/thankyou.html': typeof ThankyouDothtmlRoute
  '/lp/2-bhk': typeof Lp2BhkRoute
  '/lp/3-bhk': typeof Lp3BhkRoute
  '/lp/3-bhk-duplex': typeof Lp3BhkDuplexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy-policy.html': typeof PrivacyPolicyDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/thankyou.html': typeof ThankyouDothtmlRoute
  '/lp/2-bhk': typeof Lp2BhkRoute
  '/lp/3-bhk': typeof Lp3BhkRoute
  '/lp/3-bhk-duplex': typeof Lp3BhkDuplexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy-policy.html'
    | '/sitemap.xml'
    | '/terms.html'
    | '/thankyou.html'
    | '/lp/2-bhk'
    | '/lp/3-bhk'
    | '/lp/3-bhk-duplex'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy-policy.html'
    | '/sitemap.xml'
    | '/terms.html'
    | '/thankyou.html'
    | '/lp/2-bhk'
    | '/lp/3-bhk'
    | '/lp/3-bhk-duplex'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy-policy.html'
    | '/sitemap.xml'
    | '/terms.html'
    | '/thankyou.html'
    | '/lp/2-bhk'
    | '/lp/3-bhk'
    | '/lp/3-bhk-duplex'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyPolicyDothtmlRoute: typeof PrivacyPolicyDothtmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsDothtmlRoute: typeof TermsDothtmlRoute
  ThankyouDothtmlRoute: typeof ThankyouDothtmlRoute
  Lp2BhkRoute: typeof Lp2BhkRoute
  Lp3BhkRoute: typeof Lp3BhkRoute
  Lp3BhkDuplexRoute: typeof Lp3BhkDuplexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy.html': {
      id: '/privacy-policy.html'
      path: '/privacy-policy.html'
      fullPath: '/privacy-policy.html'
      preLoaderRoute: typeof PrivacyPolicyDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms.html': {
      id: '/terms.html'
      path: '/terms.html'
      fullPath: '/terms.html'
      preLoaderRoute: typeof TermsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou.html': {
      id: '/thankyou.html'
      path: '/thankyou.html'
      fullPath: '/thankyou.html'
      preLoaderRoute: typeof ThankyouDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/2-bhk': {
      id: '/lp/2-bhk'
      path: '/lp/2-bhk'
      fullPath: '/lp/2-bhk'
      preLoaderRoute: typeof Lp2BhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/3-bhk': {
      id: '/lp/3-bhk'
      path: '/lp/3-bhk'
      fullPath: '/lp/3-bhk'
      preLoaderRoute: typeof Lp3BhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/3-bhk-duplex': {
      id: '/lp/3-bhk-duplex'
      path: '/lp/3-bhk-duplex'
      fullPath: '/lp/3-bhk-duplex'
      preLoaderRoute: typeof Lp3BhkDuplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyPolicyDothtmlRoute: PrivacyPolicyDothtmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsDothtmlRoute: TermsDothtmlRoute,
  ThankyouDothtmlRoute: ThankyouDothtmlRoute,
  Lp2BhkRoute: Lp2BhkRoute,
  Lp3BhkRoute: Lp3BhkRoute,
  Lp3BhkDuplexRoute: Lp3BhkDuplexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
